const actionTypes = {
  FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
  FETCH_BOOKS_REQUESTED: 'FETCH_BOOKS_REQUESTED',
  FETCH_BOOKS_ERROR: 'FETCH_BOOKS_ERROR',
  FETCH_BOOK_SUCCESS: 'FETCH_BOOK_SUCCESS',
  FETCH_BOOK_REQUESTED: 'FETCH_BOOK_REQUESTED',
  FETCH_BOOK_ERROR: 'FETCH_BOOK_ERROR',
  BOOK_ADDED_TO_CART: 'BOOK_ADDED_TO_CART',
  BOOK_REMOVED_FROM_CART: 'BOOK_REMOVED_FROM_CART',
  ALL_BOOKS_REMOVED_FROM_CART: 'ALL_BOOKS_REMOVED_FROM_CART',
  MODAL_OPENED: "MODAL_OPENED",
  MODAL_CLOSED: "MODAL_CLOSED"
};

export default actionTypes;
